server:
  port: 82
  context-path: /demouat

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
        cluster:
          # （普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
          nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
          # （普通集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。
          max-redirects:
          expireSeconds: 3600



mybatis:
  type-aliases-package: com.mybatis.demo.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  path: /home/bea1/logs/mybatisdemo-uat/${server.port}/
  file: mybatisdemo
  level:
    root: INFO
    com:
      alibaba:
        dubbo: INFO
    org:
      mybatis: INFO
      springframework:
        web: INFO
