server:
  tomcat:
    uri-encoding: UTF-8

#前后端分离，前端页面地址
config:
  front:
    view : /home/bea1/fv/

spring:
  application:
    name: mybatis-demo
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    #表示所有的访问都经过静态资源路径,可以自定义，如/static/**
    static-path-pattern: /**
  resources:
    #默认加载路径classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    #自定义加载路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${config.front.view}

